---
- name: Set defaults
  set_fact:
    run_service: 
      - enabled: "None"
  when: run_service is not defined
- name: "{{ item.state }} {{ item.name }}"
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled | default(omit) }}" 
  with_items: "{{ run_service }}"
  when: item.name is defined and item.state is defined
  become: yes 
